### ISSUE TITLE
Error installing with python3.9 and numpy 1.19

### ISSUE THREAD

**Issue by eldraco** [Kitware/bat#114]
When having numpy 1.19 and python 3.9, zat tries to dowload and use numpy 1.16, but it fails and is not installing

`pip3 install zat
Collecting zat
  Using cached zat-0.3.9-py2.py3-none-any.whl (174 kB)
Collecting pyarrow
  Using cached pyarrow-2.0.0.tar.gz (58.9 MB)
  Installing build dependencies ... -
error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3ov851tb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython >= 0.29' 'numpy==1.14.5; python_version<'"'"'3.7'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"'' setuptools setuptools_scm wheel
       cwd: None
  Complete output (3557 lines):
  Ignoring numpy: markers 'python_version < "3.7"' don't match your environment
  Collecting cython>=0.29
    Using cached Cython-0.29.21-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
  Collecting numpy==1.16.0
    Using cached numpy-1.16.0.zip (5.1 MB)
  Collecting setuptools
    Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting setuptools_scm
    Using cached setuptools_scm-4.1.2-py2.py3-none-any.whl (27 kB)
  Collecting wheel
    Using cached wheel-0.36.1-py2.py3-none-any.whl (34 kB)`
(and continues the error log)

**Comment by brifordwylie** [comment]
Hmm... ZAT doesn't specify a specific version of numpy. From the output above it looks like pyarrow is having an issue... After some experimenting it looks like pyarrow has wheels for Python3.8 but does not currently have them for 3.9 (https://pypi.org/project/pyarrow/#files)... so you could either...
1) Figure out how to install/build pyarrow for your Python3.9 environment
2) Use Python3.8
3) Download the ZAT repo.. edit/remove the pyarrow from setup.py and `pip install -e .`

Obviously 3) is a hack but since pyarrow simply optimizes a few of the code paths it won't hurt not to have it (pretty sure)

Shrug, let me know how it goes.. I'm going to close this issue but I'll track pyarrow wheels and I'll update this issue when the 3.9 wheel gets supported.

**Comment by eldraco** [comment]
Thanks! will try.
