### ISSUE TITLE
Expand Bro logs Reader with Pattern and Compression Support

### ISSUE THREAD

**Issue by JackJHarris** [Kitware/bat#20]
In addition being able to load a single uncompressed file with the BroLogReader
```
reader = bro_log_reader.BroLogReader('http.log')
```

Add support for loading multiple files (with optional gz detection)

```
reader = bro_log_reader.BroLogReader('http(.*).log.gz')
```
This would facilitate loading a set of files for analysis

**Comment by brifordwylie** [comment]
Hi @JackJHarris so I'm looking at this.. and it's a little bit tricky so I'm going to do a PR for it and I'll put you on the review.

**Comment by brifordwylie** [comment]
Okay, so after doing this the wrong way with PR #21 ... I realized much better cleaner to do #22. Basically when doing multiple file or zipped file... the tail=True option doesn't make any sense. So anyway... all you do now is create a BroMultiLogReader(file_path) instead of the BroLogReader(file_path).  The multi-log reader will take a file glob (dns*.log) and it will also take gzipped files (dns.log.gz)
