### ISSUE TITLE
send data to splunk

### ISSUE THREAD

**Issue by jjjan** [Kitware/bat#24]
Hello,
how is possible to send data directly to splunk?

**Comment by brifordwylie** [comment]
Hi @jjjan  I think the easiest way is to use the Bro Kafka plugin (as described here: https://github.com/Kitware/bat/blob/master/notebooks/Bro_to_Kafka_to_Spark.ipynb and then use the Splunk add-on for Kafka: https://splunkbase.splunk.com/app/2935/

So basically two steps:

1.  Install Kafka plugin to Bro
2. Install Kafka add-on for Splunk

Let me know how it goes, I think this is a popular enough use case so that other folks will be interested as well. Perhaps I'll throw together a small notebook on how to do it.

I also noticed there's a direct Splunk Add-on for Bro
- https://splunkbase.splunk.com/app/1617/

So that may be the easiest/best way, since you don't have to run a Kafka server.

**Comment by brifordwylie** [comment]
Going to close this ticket. Splunk is pretty good about ingesting anything so probably 'out of scope' for us to send data to splunk.
