### ISSUE TITLE
Make the log name an required argument to all the examples

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#33]
@brifordwylie - did you want me to add 'required=True' for the '-f' argparse argument to all the examples? It would make it a little bit tidier.

I can do that to all of them and then add as one pull request and approve it myself if you're ok with the action?

Cheers, Mike

**Comment by brifordwylie** [comment]
@swedishmike that's a good idea, we might also just make it a positional argument... so that's it more like unix command line tools. So

    python blah.py filename

I think I like that even better, if you want to give it a swing feel free.

Here's the docs on that if you need it: https://docs.python.org/2/library/argparse.html

Approving PRs yourself is fine for smaller stuff like this, obviously just make sure all the automated tests pass and do a few yourself.

Cheers and thanks so much for contributing to the project, it's great to have the help.

**Comment by swedishmike** [comment]
Sure thing - I'll give that a go and will test it locally thoroughly before even submitting the PR for automated tests.

I'll probably submit this tomorrow - gives me time to test and 'make it right'.

Absolutely no worries at all - it's all my pleasure. It's a great project and I'm happy that I can contribute in a small way. 

Cheers, Mike

**Comment by brifordwylie** [comment]
You probably know all this already but since your a dev on the project you can just check out this repo make a local branch and then push that local branch and make a PR

    $ git checkout -b my_branch
    <work on stuff>
    $ git push -u origin my_branch

**Comment by swedishmike** [comment]
Yeah - just wanted to check that it was ok with you to do it that way and just didn't get around to it yet. ;)

Will do that from now on.

**Comment by swedishmike** [comment]
@brifordwylie All tested and merged now. Have a look and see what you think - if you're happy with it let me know and I'll close this issue.

**Comment by brifordwylie** [comment]
Looks great :)
