### ISSUE TITLE
Not sure if this is a bug or just me misunderstanding things.

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#44]
I tried to generate some graphs from the conn.log file when I ran into some problems.

If I follow the 'Bro_to_Plot.ipynb' framework and try the following:

`conn_df['duration'].hist()`

It bombs out with quite a lot of error output which culminates with: 

`TypeError: Cannot cast ufunc less input from dtype('float64') to dtype('<m8[ns]') with casting rule 'same_kind'`

Some Googling later I tried with the following:

`conn_df.duration = conn_df.duration.astype('timedelta64')`

Once I did that the plot displayed properly.

I'm still very much a beginner when it comes to Pandas so I'm not sure if the problem lies in the generation of the Dataframe and the 'type assignment' or if it is something else?

**Comment by brifordwylie** [comment]
Hi @swedishmike,

Thanks for finding this. Looking at the types of the conn_df.. I see that the type of the duration is timedelta64[ns].. which seems correct. 
```
conn_df.dtypes
Out[10]:
conn_state                 object
duration          timedelta64[ns]
history                    object
...
```
I'm not a time delta expert but I found a conversion/overflow issue described here: http://www.datasciencebytes.com/bytes/2015/05/16/pandas-timedelta-histograms-unit-conversion-and-overflow-danger/

So when I convert this to a time in seconds or milliseconds, as you stated above, the plot works fine. I would definitely put in the [s] or [ms] arg to timedelta64 so that you explicitly know what you're getting.

```
conn_df['duration'] = conn_df['duration'].astype('timedelta64[ms]')
```

I'm not sure this is really a bug.. just perhaps a known issue with time deltas and plotting, so I'm going to close this. But I am going to create an issue that documents this and gives examples of plotting time deltas. (new issue is #46)
